version: "3.8"
services:
 springboot-app:
  container_name: app
  image: springboot-app
  restart: always
  build: .
  ports:
  - 7070:6969
  environment:
   MYSQL_HOST: mysqldb
   MYSQL_USER: root
   MYSQL_PASSWORD: root
   MYSQL_PORT: 3306
   
  
 
 mysqlbd:
  container_name: mysqldb
  image: mysql
  volumes:
   - C:\Users\Faiz\Desktop\SQLDATA:/var/lib/mysql
  ports:
  - 3307:3306
  environment:
   MYSQL_DATABASE: test
   MYSQL_ROOT_PASSWORD: root
   